create TABLE users(
                      id int GENERATED BY DEFAULT as identity PRIMARY KEY ,
                      username varchar(100) not null unique ,
                      password varchar(100) not null,
                      email varchar(100) not null,
                      rate double precision
);
create TABLE pastes(
                       id int generated by default as identity PRIMARY KEY ,
                       name varchar(100) not null unique ,
                       rate double precision,
                       views int,
                       text varchar,
                       user_id int references users(id) on DELETE SET NULL,
                       created_at timestamp,
                       expiration_at timestamp
)

create table roles (
                       id                    int GENERATED BY DEFAULT as identity PRIMARY KEY,
                       name                  varchar(50) not null,
                       primary key (id)
);
CREATE TABLE users_roles (
                             user_id               bigint not null,
                             role_id               int not null,
                             primary key (user_id, role_id),
                             foreign key (user_id) references users (id),
                             foreign key (role_id) references roles (id)
);
